export const data = [
  { id: 1, nome: "João Silva", email: "joao@example.com", telefone: "(11) 1234-5678", endereco: "Rua A, 123", cidade: "São Paulo", estado: "SP" },
  { id: 2, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 3, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 4, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 5, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 6, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 7, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 8, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 9, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 10, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 11, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 12, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 13, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 14, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 15, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 16, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 17, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 18, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 19, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
  { id: 20, nome: "Maria Santos", email: "maria@example.com", telefone: "(21) 9876-5432", endereco: "Av. B, 456", cidade: "Rio de Janeiro", estado: "RJ" },
]